services:
  front:
    build: ./front
    container_name: translation-front
    restart: always
    networks:
      - traefik_public
      - internal
    labels:
      - "traefik.enable=true"

      # LAN access
      - "traefik.http.routers.translation-local.rule=Host(`translation.server.local`)"
      - "traefik.http.routers.translation-local.entrypoints=websecure"
      - "traefik.http.routers.translation-local.tls=true"
      - "traefik.http.routers.translation-local.tls.certresolver=letsencrypt"
      - "traefik.http.routers.translation-local.middlewares=auth@file"
      - "traefik.http.routers.translation-local.service=translation-front-service"
      - "traefik.http.services.translation-front-service.loadbalancer.server.port=80"

      # External access DuckDNS
      - "traefik.http.routers.translation-duckdns.rule=Host(`translation.drannoc.duckdns.org`)"
      - "traefik.http.routers.translation-duckdns.entrypoints=websecure"
      - "traefik.http.routers.translation-duckdns.tls.certresolver=letsencrypt"
      - "traefik.http.routers.translation-duckdns.service=translation-front-service"

  back:
    build: ./back
    container_name: translation-back
    restart: always
    networks:
      - traefik_public
      - internal
    volumes:
      - translation_db:/app/data
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.translation-back.rule=Host(`translation.drannoc.duckdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.translation-back.entrypoints=websecure"
      - "traefik.http.routers.translation-back.tls.certresolver=letsencrypt"
      - "traefik.http.routers.translation-back.service=translation-back-service"
      - "traefik.http.services.translation-back-service.loadbalancer.server.port=3001"
      - "traefik.http.routers.translation-back.middlewares=translation-back-strip"
      - "traefik.http.middlewares.translation-back-strip.stripprefix.prefixes=/api"

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: always
    networks:
      - internal
    volumes:
      - libretranslate_models:/data
      - libretranslate_cache:/app/cache
    environment:
      - LT_LOAD_ONLY=en,fr,es,de,it,nl,pt,ja
      - LT_UPDATE_MODELS=true

volumes:
  translation_db:
    name: translation-tool-database
  libretranslate_models:
    name: translation-tool-lt-models
  libretranslate_cache:
    name: translation-tool-lt-cache

networks:
  traefik_public:
    external: true
  internal:
    name: translation-tool-network
    driver: bridge
