services:
  front:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - back
    restart: unless-stopped

  back:
    build: ./back
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - translation_db:/app/data
    environment:
      - NODE_ENV=production

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    volumes:
      - libretranslate_models:/data
      - libretranslate_cache:/app/cache
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,fr,es,de,it,nl,pt,ja
      - LT_UPDATE_MODELS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      retries: 20

# Persistants data volumes
volumes:
  translation_db:
    driver: local
    name: translation-tool_db # Fixed name to avoid conflicts

  libretranslate_models:
    driver: local
    name: translation-tool_models

  libretranslate_cache:
    driver: local
    name: translation-tool_cache
