const ACTIONS = {
  SET_PROJECTS: 'SET_PROJECTS',
  SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
  SET_TRANSLATIONS: 'SET_TRANSLATIONS',
  SET_SELECTED_LANGUAGES: 'SET_SELECTED_LANGUAGES',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_LOADING: 'SET_LOADING',
  UPDATE_TRANSLATION_VALUE: 'UPDATE_TRANSLATION_VALUE',
  ADD_TRANSLATION: 'ADD_TRANSLATION',
  UPDATE_TRANSLATION: 'UPDATE_TRANSLATION',
  REMOVE_TRANSLATION: 'REMOVE_TRANSLATION',
  SET_FILTER: 'SET_FILTER',
  SET_SORT: 'SET_SORT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  SET_VIEW_MODE: 'SET_VIEW_MODE',
  ADD_PROJECT: 'ADD_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
};

export default ACTIONS;
